# Generated by Django 4.0 on 2024-04-16 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoruseSchedules',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_no', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='courses_images')),
                ('description', models.CharField(max_length=255)),
                ('instractor', models.CharField(default='', max_length=30)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='studentsReg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.students')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='core.courses')),
                ('course_prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requires', to='core.courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='prerequisites',
            field=models.ManyToManyField(through='core.Prerequisties', to='core.Courses'),
        ),
        migrations.AddField(
            model_name='courses',
            name='schedule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coruseschedules'),
        ),
    ]
