# Generated by Django 5.0.4 on 2024-05-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coruseschedules',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentsreg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
